-- Insert placeholder featured deal with corrected cap_rate
INSERT INTO public.deals (
  deal_name,
  deal_id,
  deal_status,
  transaction_type,
  deal_value,
  property_name,
  property_type,
  city,
  state_province,
  country,
  buyer,
  seller,
  announcement_date,
  closing_date,
  square_footage,
  cap_rate,
  occupancy_rate,
  image_url,
  featured_deal,
  published
) VALUES (
  'Manhattan Office Tower Acquisition',
  'FEAT-001',
  'Closed',
  'Acquisition',
  2800000000,
  'Manhattan Office Tower',
  'Office',
  'New York',
  'NY',
  'USA',
  'Blackstone Group',
  'Brookfield Properties',
  '2024-12-12',
  '2024-12-12',
  1200000,
  0.052,
  0.94,
  'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
  true,
  true
);

-- Insert placeholder recent deal
INSERT INTO public.deals (
  deal_name,
  deal_id,
  deal_status,
  transaction_type,
  deal_value,
  property_name,
  property_type,
  city,
  state_province,
  country,
  buyer,
  seller,
  announcement_date,
  closing_date,
  image_url,
  recent_deal,
  published
) VALUES (
  'The Spiral Tower Transaction',
  'REC-001',
  'Closed',
  'Sale',
  4200000000,
  'The Spiral Tower',
  'Office',
  'New York',
  'NY',
  'USA',
  'Hudson Capital Partners',
  'Related Companies',
  '2024-12-15',
  '2024-12-15',
  'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&q=80',
  true,
  true
);

-- Insert placeholder pipeline deal
INSERT INTO public.deals (
  deal_name,
  deal_id,
  deal_status,
  transaction_type,
  deal_value,
  property_name,
  property_type,
  city,
  state_province,
  country,
  announcement_date,
  image_url,
  pipeline_deal,
  published
) VALUES (
  'Seattle Waterfront Development',
  'PIP-001',
  'Marketing',
  'Development',
  1200000000,
  'Seattle Waterfront Development',
  'Mixed-Use',
  'Seattle',
  'WA',
  'USA',
  '2025-01-15',
  'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
  true,
  true
);