// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvporfbxxtgzxtjqtelz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2cG9yZmJ4eHRnenh0anF0ZWx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MjU5ODksImV4cCI6MjA2ODEwMTk4OX0.I0Us7J8XE5mCbriePwuRDb8VYkF8__x-bs7A8gfgaXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});